version: 3

tasks:
  build: 
    cmds:
      - go build .
  snapshot: 
    cmds:
      - goreleaser --snapshot
  test:
    cmds: 
      - go test -v ./client ./cmd {{.CLI_ARGS}}
  docs-serve: 
    cmds: 
      - docker run -it -p 8000:8000 -v $(pwd):/docs squidfunk/mkdocs-material serve -a 0.0.0.0:8000